name: Docker Build, Test, and Push

on:
  push:
    branches: [main]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        
    - name: Restore dependencies
      run: dotnet restore ./sportnoDrustvo.sln

    - name: Run tests
      run: dotnet test ./sportnoDrustvoTests/sportnoDrustvoTests.csproj --no-restore

    - name: Build Docker Image
      run: docker build -t realfoodie/sportnodrustvo:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push realfoodie/sportnodrustvo:latest